## LAZY FRAME AGREGACIONES

In [2]:
import polars as pl
from polars import col

In [3]:
path = ('/content/vuelos.parquet')

In [6]:
lf = pl.LazyFrame(
    {
        'id': [1,2,3],
        'nombre':['juan','pedro','maria']
    }
)

In [7]:
lf

In [8]:
lf.collect()

shape: (3, 2)
┌─────┬────────┐
│ id  ┆ nombre │
│ --- ┆ ---    │
│ i64 ┆ str    │
╞═════╪════════╡
│ 1   ┆ juan   │
│ 2   ┆ pedro  │
│ 3   ┆ maria  │
└─────┴────────┘

In [14]:
df = pl.read_parquet('/content/vuelos.parquet')
df

shape: (5_819_079, 31)
┌──────┬───────┬─────┬─────────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ YEAR ┆ MONTH ┆ DAY ┆ DAY_OF_WEEK ┆ … ┆ SECURITY_DEL ┆ AIRLINE_DELA ┆ LATE_AIRCRAF ┆ WEATHER_DELA │
│ ---  ┆ ---   ┆ --- ┆ ---         ┆   ┆ AY           ┆ Y            ┆ T_DELAY      ┆ Y            │
│ i32  ┆ i32   ┆ i32 ┆ i32         ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│      ┆       ┆     ┆             ┆   ┆ i32          ┆ i32          ┆ i32          ┆ i32          │
╞══════╪═══════╪═════╪═════════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 2015 ┆ 1     ┆ 1   ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 1     ┆ 1   ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 1     ┆ 1   ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 1     ┆ 1   ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 1     ┆ 1   ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ …    ┆ …     ┆ …   ┆ …           ┆ … ┆ …            ┆ …            ┆ …            ┆ …            │
│ 2015 ┆ 12    ┆ 31  ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 12    ┆ 31  ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 12    ┆ 31  ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 12    ┆ 31  ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
│ 2015 ┆ 12    ┆ 31  ┆ 4           ┆ … ┆ null         ┆ null         ┆ null         ┆ null         │
└──────┴───────┴─────┴─────────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [15]:
df.columns

['YEAR',
 'MONTH',
 'DAY',
 'DAY_OF_WEEK',
 'AIRLINE',
 'FLIGHT_NUMBER',
 'TAIL_NUMBER',
 'ORIGIN_AIRPORT',
 'DESTINATION_AIRPORT',
 'SCHEDULED_DEPARTURE',
 'DEPARTURE_TIME',
 'DEPARTURE_DELAY',
 'TAXI_OUT',
 'WHEELS_OFF',
 'SCHEDULED_TIME',
 'ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'WHEELS_ON',
 'TAXI_IN',
 'SCHEDULED_ARRIVAL',
 'ARRIVAL_TIME',
 'ARRIVAL_DELAY',
 'DIVERTED',
 'CANCELLED',
 'CANCELLATION_REASON',
 'AIR_SYSTEM_DELAY',
 'SECURITY_DELAY',
 'AIRLINE_DELAY',
 'LATE_AIRCRAFT_DELAY',
 'WEATHER_DELAY']

In [21]:
query = (
    pl.scan_parquet('/content/vuelos.parquet')
    .select(
        col('AIRLINE_DELAY'),
        col('SECURITY_DELAY'),
        col('WEATHER_DELAY'), #Fixed typo in column name
    )
    .null_count()  ### recuento de valores nulos de cada columna
)
query.collect()

shape: (1, 3)
┌───────────────┬────────────────┬───────────────┐
│ AIRLINE_DELAY ┆ SECURITY_DELAY ┆ WEATHER_DELAY │
│ ---           ┆ ---            ┆ ---           │
│ u32           ┆ u32            ┆ u32           │
╞═══════════════╪════════════════╪═══════════════╡
│ 4755640       ┆ 4755640        ┆ 4755640       │
└───────────────┴────────────────┴───────────────┘

In [22]:
vuelos_lf =(
    pl.scan_parquet(path)
    .select(
     col('AIR_TIME'),
     col('DISTANCE')
)
)
vuelos_lf.sum().collect()  ## suma de los valores de cada columna

shape: (1, 2)
┌───────────┬───────────┐
│ AIR_TIME  ┆ DISTANCE  │
│ ---       ┆ ---       │
│ i32       ┆ i32       │
╞═══════════╪═══════════╡
│ 648606351 ┆ 490390113 │
└───────────┴───────────┘

In [20]:
vuelos_lf.max().collect()

shape: (1, 2)
┌──────────┬──────────┐
│ AIR_TIME ┆ DISTANCE │
│ ---      ┆ ---      │
│ i32      ┆ i32      │
╞══════════╪══════════╡
│ 690      ┆ 4983     │
└──────────┴──────────┘

In [23]:
vuelos_lf.mean().collect()

shape: (1, 2)
┌────────────┬────────────┐
│ AIR_TIME   ┆ DISTANCE   │
│ ---        ┆ ---        │
│ f64        ┆ f64        │
╞════════════╪════════════╡
│ 113.511628 ┆ 822.356495 │
└────────────┴────────────┘

In [24]:
vuelos_lf.min().collect()

shape: (1, 2)
┌──────────┬──────────┐
│ AIR_TIME ┆ DISTANCE │
│ ---      ┆ ---      │
│ i32      ┆ i32      │
╞══════════╪══════════╡
│ 7        ┆ 21       │
└──────────┴──────────┘