<a href="https://colab.research.google.com/github/Viny2030/polars/blob/main/Lectura54.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##MISCELANEA-SQL EN POLARS

In [57]:
import polars as pl

In [58]:
df = pl.DataFrame(
    {
        'id': [1,2,3],
        'color':['rojo','verde','azul'],

    }
)

In [59]:
lf = pl.LazyFrame(
    {
        'letra': ['a','b','c'],
        'conteo':[6,9,3],

    }
)

In [60]:
df

shape: (3, 2)
┌─────┬───────┐
│ id  ┆ color │
│ --- ┆ ---   │
│ i64 ┆ str   │
╞═════╪═══════╡
│ 1   ┆ rojo  │
│ 2   ┆ verde │
│ 3   ┆ azul  │
└─────┴───────┘

In [61]:
lf

In [62]:
ctx = pl.SQLContext()

In [63]:
ctx = pl.SQLContext(register_globals=True)

In [64]:
ctx.tables()

['_',
 '_17',
 '_19',
 '_20',
 '_33',
 '_34',
 '_4',
 '_46',
 '_48',
 '_49',
 '_5',
 '_60',
 '_61',
 '__',
 'df',
 'df1',
 'df2',
 'df3',
 'lf']

In [65]:
ctx = pl.SQLContext(frames={'df_color': df, 'df_letras': lf})
ctx.tables()

['df_color', 'df_letras']

In [66]:
ctx = pl.SQLContext(df1=df, df2=lf)

In [67]:
ctx.tables()

['df1', 'df2']

In [68]:
df1 = pl.DataFrame({'a':[1]})
df2 = pl.DataFrame({'b':[2]})
df3 = pl.DataFrame({'c':[3]})

In [69]:
ctx.register('df_1',df1)
ctx.tables()

['df1', 'df2', 'df_1']

In [70]:
ctx.register_many({'df_2':df2, 'df_3': df3})
ctx.tables()

['df1', 'df2', 'df_1', 'df_2', 'df_3']

In [71]:
ctx.unregister(['df1','df_1','df_2'])
ctx.tables()

['df2', 'df_3']

In [72]:
ctx = pl.SQLContext(register_globals=True, eager_execution=True)

<ipython-input-72-c0e62b438ec9>:1: DeprecationWarning: The argument `eager_execution` for `SQLContext.__init__` is deprecated. It has been renamed to `eager`.
  ctx = pl.SQLContext(register_globals=True, eager_execution=True)

In [73]:
ctx.execute("SELECT * FROM df")

shape: (3, 2)
┌─────┬───────┐
│ id  ┆ color │
│ --- ┆ ---   │
│ i64 ┆ str   │
╞═════╪═══════╡
│ 1   ┆ rojo  │
│ 2   ┆ verde │
│ 3   ┆ azul  │
└─────┴───────┘

In [74]:
ctx = pl.SQLContext(register_globals=True)

In [75]:
ctx.execute("SELECT * FROM df", eager=True)

shape: (3, 2)
┌─────┬───────┐
│ id  ┆ color │
│ --- ┆ ---   │
│ i64 ┆ str   │
╞═════╪═══════╡
│ 1   ┆ rojo  │
│ 2   ┆ verde │
│ 3   ┆ azul  │
└─────┴───────┘

In [76]:
ctx.execute("SELECT * FROM lf WHERE conteo >= 6").collect()

shape: (2, 2)
┌───────┬────────┐
│ letra ┆ conteo │
│ ---   ┆ ---    │
│ str   ┆ i64    │
╞═══════╪════════╡
│ a     ┆ 6      │
│ b     ┆ 9      │
└───────┴────────┘

# **##LECTURA 55-SQL EN POLARS II**

In [77]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [78]:
with pl.SQLContext(df=df,lf=lf) as ctx:
  ctx.register_many(df1=df1,df2=df2,df3=df3)
  print(ctx.tables())

['df', 'df1', 'df2', 'df3', 'lf']

In [79]:
ctx.tables()

['df', 'lf']

In [80]:
juegos = pl.read_csv('/content/drive/MyDrive/polars/seccion08/games.csv'),
ligas = pl.read_csv('/content/drive/MyDrive/polars/seccion08/leagues.csv'),

In [81]:
juegos

(shape: (42_272, 15)
 ┌─────────┬────────────┬────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
 │ game_id ┆ competitio ┆ season ┆ round      ┆ … ┆ stadium    ┆ attendance ┆ referee   ┆ url       │
 │ ---     ┆ n_code     ┆ ---    ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
 │ i64     ┆ ---        ┆ i64    ┆ str        ┆   ┆ str        ┆ i64        ┆ str       ┆ str       │
 │         ┆ str        ┆        ┆            ┆   ┆            ┆            ┆           ┆           │
 ╞═════════╪════════════╪════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
 │ 2457642 ┆ NLSC       ┆ 2014   ┆ Final      ┆ … ┆ Johan      ┆ 42000      ┆ Danny     ┆ https://w │
 │         ┆            ┆        ┆            ┆   ┆ Cruijff    ┆            ┆ Makkelie  ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆ ArenA      ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 │ 2639088 ┆ BESC       ┆ 2013   ┆ Final      ┆ … ┆ Constant   ┆ 13733      ┆ Jonathan  ┆ https://w │
 │         ┆            ┆        ┆            ┆   ┆ Vanden     ┆            ┆ Lardot    ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆ Stock      ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆ Stadion    ┆            ┆           ┆ o.u…      │
 │ 2481145 ┆ SUC        ┆ 2014   ┆ final 1st  ┆ … ┆ Santiago   ┆ 75897      ┆ Estrada   ┆ https://w │
 │         ┆            ┆        ┆ leg        ┆   ┆ Bernabéu   ┆            ┆ Fernández ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 │ 2484338 ┆ POSU       ┆ 2014   ┆ Final      ┆ … ┆ Estádio    ┆ 30000      ┆ Duarte    ┆ https://w │
 │         ┆            ┆        ┆            ┆   ┆ Municipal  ┆            ┆ Gomes     ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆ de Aveiro  ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 │ 2502472 ┆ FRCH       ┆ 2014   ┆ Final      ┆ … ┆ Workers    ┆ 39752      ┆ Clément   ┆ https://w │
 │         ┆            ┆        ┆            ┆   ┆ Stadium    ┆            ┆ Turpin    ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 │ …       ┆ …          ┆ …      ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
 │ 3580217 ┆ DK1        ┆ 2021   ┆ 9.         ┆ … ┆ Parken     ┆ 34378      ┆ Jakob     ┆ https://w │
 │         ┆            ┆        ┆ Matchday   ┆   ┆            ┆            ┆ Kehlet    ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 │ 3580204 ┆ DK1        ┆ 2021   ┆ 6.         ┆ … ┆ Cepheus    ┆ 4906       ┆ Mikkel    ┆ https://w │
 │         ┆            ┆        ┆ Matchday   ┆   ┆ Park       ┆            ┆ Redder    ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆ Randers    ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 │ 3580262 ┆ DK1        ┆ 2021   ┆ 13.        ┆ … ┆ JYSK Park  ┆ 3662       ┆ Sandi     ┆ https://w │
 │         ┆            ┆        ┆ Matchday   ┆   ┆            ┆            ┆ Putros    ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 │ 3580188 ┆ DK1        ┆ 2021   ┆ 4.         ┆ … ┆ Parken     ┆ 31297      ┆ Mads-Kris ┆ https://w │
 │         ┆            ┆        ┆ Matchday   ┆   ┆            ┆            ┆ toffer    ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆ Kristoffe ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆ rsen      ┆ o.u…      │
 │ 3580176 ┆ DK1        ┆ 2020   ┆ 2.         ┆ … ┆ Right to   ┆ 2213       ┆ Aydin     ┆ https://w │
 │         ┆            ┆        ┆ Matchday   ┆   ┆ Dream Park ┆            ┆ Uslu      ┆ ww.transf │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ ermarkt.c │
 │         ┆            ┆        ┆            ┆   ┆            ┆            ┆           ┆ o.u…      │
 └─────────┴────────────┴────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘,)

In [82]:
ligas

(shape: (14, 3)
 ┌───────────┬──────────────────────┬───────────────┐
 │ league_id ┆ name                 ┆ confederation │
 │ ---       ┆ ---                  ┆ ---           │
 │ str       ┆ str                  ┆ str           │
 ╞═══════════╪══════════════════════╪═══════════════╡
 │ L1        ┆ bundesliga           ┆ europa        │
 │ NL1       ┆ eredivisie           ┆ europa        │
 │ BE1       ┆ jupiler-pro-league   ┆ europa        │
 │ ES1       ┆ laliga               ┆ europa        │
 │ PO1       ┆ liga-nos             ┆ europa        │
 │ …         ┆ …                    ┆ …             │
 │ SC1       ┆ scottish-premiership ┆ europa        │
 │ IT1       ┆ serie-a              ┆ europa        │
 │ GR1       ┆ super-league-1       ┆ europa        │
 │ TR1       ┆ super-lig            ┆ europa        │
 │ DK1       ┆ superligaen          ┆ europa        │
 └───────────┴──────────────────────┴───────────────┘,)

In [83]:
with pl.SQLContext(
    juegos = pl.scan_csv('/content/drive/MyDrive/polars/seccion08/games.csv'),
    ligas = pl.scan_csv('/content/drive/MyDrive/polars/seccion08/leagues.csv'),
    eager_execution= True
) as ctx:
    query = """
  SELECT
    name,
    count(*) AS conteo
  FROM juegos
  LEFT JOIN ligas ON juegos.game_id = ligas.league_id(i64)
  GROUP BY name
  ORDER BY conteo DESC
  """


print(ctx.execute(query))

<ipython-input-83-e2cdbff0b830>:1: DeprecationWarning: The argument `eager_execution` for `SQLContext.__init__` is deprecated. It has been renamed to `eager`.
  with pl.SQLContext(

SQLInterfaceError: unsupported SQL join constraint:
On(BinaryOp { left: CompoundIdentifier([Ident { value: "juegos", quote_style: None }, Ident { value: "game_id", quote_style: None }]), op: Eq, right: Function(Function { name: ObjectName([Ident { value: "ligas", quote_style: None }, Ident { value: "league_id", quote_style: None }]), parameters: None, args: List(FunctionArgumentList { duplicate_treatment: None, args: [Unnamed(Expr(Identifier(Ident { value: "i64", quote_style: None })))], clauses: [] }), filter: None, null_treatment: None, over: None, within_group: [] }) })

In [ ]:
with pl.SQLContext(eager_execution=True) as ctx:
    query = """
    SELECT *
    FROM read_csv('/content/drive/MyDrive/polars/seccion08/games.csv')
    """

    print(ctx.execute(query))

# **##LECTURAS 56-SQL GRAFICAS EN POLARS

In [ ]:
import polars as pl
from  polars import col

In [ ]:
vuelos_lf = pl.scan_parquet('/content/drive/MyDrive/polars/seccion05/vuelos/vuelos.parquet')

In [ ]:
vuelos_lf.collect()

In [ ]:
aerolinea_vs_tiempo_de_aire = vuelos_lf.group_by('AIRLINE').agg(
    AVG_AIR_TIME=col('AIR_TIME').mean()
).collect()

In [ ]:
aerolinea_vs_tiempo_de_aire

In [ ]:
vuelos_AA_DL = vuelos_lf.filter(
    (col('AIRLINE') == 'AA') | (col('AIRLINE') == 'DL')
).collect()

In [ ]:
vuelos_AA_DL

In [ ]:
hexagonal_data = vuelos_lf.select(
    col('AIRLINE'),
    col('ARRIVAL_DELAY')
).collect()

In [ ]:
hexagonal_data

In [ ]:
departure_delay_day = vuelos_lf.select(
    col('DAY'),
    col('AIRLINE'),
    col('DEPARTURE_DELAY')
).collect()

In [ ]:
departure_delay_day

metodo plot con huvplot

https://hvplot.holoviz.org/getting_started/installation.html

In [84]:
!python -m venv my_env
!source my_env/bin/activate

The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /content/my_env/bin/python3

/bin/bash: line 1: my_env/bin/activate: No such file or directory

In [85]:
!pip install --upgrade altair>=5.4.0

In [ ]:
!pip install hvplot

In [ ]:
import altair

In [ ]:
!pip install --force-reinstall altair>=5.4.0

In [ ]:
!pip install altair==5.4.0
import altair
print(altair.__version__)

In [ ]:
aerolinea_vs_tiempo_de_aire.plot.bar(x='AIRLINE',
                                     y='AVG_AIR_TIME'
)

In [ ]:
vuelos_AA_DL

In [ ]:
!pip install altair==5.4.0

In [ ]:
# Verify the installed version of Altair
print(f"Altair version: {altair.__version__}")

In [ ]:
vuelos_AA_DL.plot.hist(
    x='AIRLINE',
    y='ARRIVAL_DELAY',
    bins=20,
    bins_range=(-20,100),
    width=300,
    subplots=True
)

In [86]:
import plotly.express as px
import hvplot.pandas

ModuleNotFoundError: No module named 'hvplot'

In [ ]:
 fig =px.histogram(vuelos_AA_DL,
    x='AIRLINE',
    y='ARRIVAL_DELAY',
    nbins=20,
    range_x=[-20,100],
    width=300,
    facet_col='AIRLINE',
)
 fig.show()

In [ ]:
fig = px.bar(aerolinea_vs_tiempo_de_aire,
                            x='AIRLINE',
                        y='AVG_AIR_TIME'
)
fig.show()

In [ ]:
fig = px.scatter(vuelos_AA_DL,
           x='DISTANCE',
           y='DEPARTURE_DELAY',
           color='AIRLINE',
           opacity=0.2  # Use 'opacity' instead of 'alpha'
           )
fig.show()

In [ ]:
import plotly.figure_factory as ff

In [ ]:
fig = ff.create_hexbin_mapbox(
    data_frame=vuelos_AA_DL,
    lat='LATITUDE',  # Replace with your latitude column
    lon='LONGITUDE', # Replace with your longitude column
    nx_hexagon=20,
    opacity=0.5,
    labels={'color': 'Count'},
    min_count=1,
    mapbox_style="carto-positron"
)
fig.show()

In [ ]:
fig = ff.create_hexbin_mapbox(
    data_frame=vuelos_AA_DL,  # Assuming your DataFrame is named 'vuelos_AA_DL'
    lat='ARRIVAL_DELAY',  # Replace with the column containing latitude data
    lon='AIRLINE',        # Replace with the column containing longitude data
    nx_hexagon=20,       # Number of hexagons along the x-axis
    opacity=0.5,          # Opacity of the hexagons
    labels={'color': 'Count'},  # Label for the color scale
    min_count=1,          # Minimum count for a hexagon to be displayed
    mapbox_style="carto-positron"  # Choose a map style
)
fig.show()

In [ ]:
departure_delay_day.plot.heatmap(
       x= 'DAY',
           y= 'AIRLINE',
           c=  'DEPARTURE_DELAY',
           reduce_function=np.mean

)

In [ ]:
import plotly.graph_objects as go # Import plotly.graph_objects
import numpy as np


# Assuming your data is in a DataFrame called 'departure_delay_day'
fig = go.Figure(data=go.Heatmap(
                   z=departure_delay_day['DEPARTURE_DELAY'],
                   x=departure_delay_day['DAY'],
                   y=departure_delay_day['AIRLINE'],
                   colorscale='Viridis')) # Create a heatmap using go.Heatmap

fig.update_layout(title='Departure Delay Heatmap') # Update the layout with a title

fig.show() # Show the figure

matplotlib

convierte en un array de numpy

In [ ]:
aerolinea_vs_tiempo_de_aire

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.bar(
    x=aerolinea_vs_tiempo_de_aire['AIRLINE'],
    height= aerolinea_vs_tiempo_de_aire['AVG_AIR_TIME'],
)
plt.xlabel('Aerolinea')
plt.ylabel('Tiempo de Vuelo')
plt.title('Tiempo de Vuelo por Aerolinea')
plt.show()

In [ ]:
departure_delay_day

In [ ]:
plt.plot(
         departure_delay_day['DAY'],
         departure_delay_day['DEPARTURE_DELAY'],
         'D-r'
)
plt.xlabel('MES')
plt.ylabel('Promedio de  retrasos')
plt.title('Promedio de  retrasos  en salidas de AA')
plt.title('Promedio de  retrasos  en salidas de AA')

In [ ]:
px.bar(
      aerolinea_vs_tiempo_de_aire,
      x='AIRLINE',
      y='AVG_AIR_TIME'
)

In [ ]:
px.line(
      aerolinea_vs_tiempo_de_aire,
      x='AIRLINE',
      y='AVG_AIR_TIME',
      markers=True,
      title= 'Promedio de  retrasos  en salidas de AA'
)